require 'slack-ruby-bot'
require 'ruby-bot/bot'
require 'ruby-bot/commands/say_hello'
require 'ruby-bot/commands/weather_report'
require 'ruby-bot/commands/random_quotes'
require 'ruby-bot/commands/covid'
